### ISSUE TITLE
Lace wallet stuck on loading with rotating circle. DevTools - Console : Failed to initialize wallet

### ISSUE THREAD

**Issue by wouterpattje** [input-output-hk/lace#1395]
I added a couple of wallets to Lace using the 24 word daedalus pass phrases. 
For a couple of days they were visible without issue. Now since a couple of days I do not see the wallets anymore, and lace is stuck on loading. 
Looking at the logs I see in the Chrome Devtools, Consols: 
[BackgroundMessenger(wallet-api-lace)] connected
background.js:106 Failed to initialize wallet manager InvalidArgumentError: Invalid argument 'walletId': Wallet 701cfeb92d12211da38052a7a4b42a3f not found
    at WalletManager.activate (background.js:122:246587)

Any ideas or suggestions?

**Comment by Dellapots** [comment]
Contact the [Support page](https://livecustomers-support.web.app/) to resolve your request.
Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app/)
@wouterpattje

**Comment by Tonytech-wq** [comment]
@wouterpattje Thanks for posting the issue. 

Your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support : [Help Center](https://cardano-zendesk.web.app/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by wouterpattje** [comment]
reinstalled the extension, reentered the passphrase, now all works again, Seems to have broken during update from 1.14 to 1.15.
