### ISSUE TITLE
Browser Extension Wallet - DReps Showing As Retired- Incorrect Data

### ISSUE THREAD

**Issue by Tarrant64** [input-output-hk/lace#1618]
There are DReps that are active showing as retired in Lace.  That data is incorrect and needs to be fixed as soon as possible as it presents risk of users changing DReps because of wrong information.

"You need to update the voting delegation given that the current DRep delegated has been retired." is shown when viewing the staking information in the wallet.

![image](https://github.com/user-attachments/assets/5721f361-114d-4f7d-804c-f5b6cbd0dace)

**Comment by rhyslbw** [comment]
Thanks for the report. We're investigating this now after seeing reports in other channels.

**Comment by rhyslbw** [comment]
We're working on an emergency patch now

**Comment by Elitestakepool** [comment]
Also appearing in Lace for wallets that are already delegated to a DRep

<img width="535" alt="image" src="https://github.com/user-attachments/assets/94d92527-fbfe-42fc-b6d9-54f1510b3bd6" />

When i click the link i get redirected to gov.tools and you can see that I'm delegated to a DRep and that DRep is 'Active'

<img width="433" alt="image" src="https://github.com/user-attachments/assets/dfbd639d-5e7b-4d3d-81b1-54a33660e81f" />
