### ISSUE TITLE
getUnusedAddresses() function from Dapp Connector is returning empty array

### ISSUE THREAD

**Issue by SorinC6** [input-output-hk/lace#205]
After connecting to the dapp api and calling `getUnusedAddresses()` I always get an empty array but as the protocol described it should return the hex addresses 

```
api.getUnusedAddresses(): Promise\
Errors: APIError
Returns a list of unused addresses controlled by the wallet. 
```

**Comment by mchappell** [comment]
@SorinC6 Could you provide some more context for us please so I can investigate further

Was this from using a wallet created in Lace or elsewhere?
Was this using a mnemonic or hardware device (if hardware please specify which)?

**Comment by mchappell** [comment]
Closing as stale, unreproducible, will re-open if more information can be provided.
