### ISSUE TITLE
`signData` function from CIP30 api doesn't throw error when user cancel signing

### ISSUE THREAD

**Issue by SeungheonOh** [input-output-hk/lace#34]
When user cancel signing the dApp connector prompt, `signData` function needs to throw error to notify the app that user declined the transaction. 

Specified at https://cips.cardano.org/cips/cip30/#errortypes `TxSignError` type

Currently, Lace doesn't throw error, and thus application fails to recognize that user declined to sign.

**Comment by mchappell** [comment]
Also updated/checked in Also added in #816
