### ISSUE TITLE
`signTx` probably leaks an async exception on cancelation (instead of rejection) 

### ISSUE THREAD

**Issue by paluh** [input-output-hk/lace#60]
Hi,

Thanks for building Lace!

When I'm testing `signTx` and I cancel the operation from Lace I'm getting (probably [leaking js-sdk error](
https://github.com/input-output-hk/cardano-js-sdk/blob/19cabfee1cd439ebd729d0a8e9a1c58fd16a1b13/packages/wallet/src/cip30.ts#L384)):

```
Uncaught (in promise) Error {code: 2, info: 'user declined signing tx', name: 'eo', message: '', stack: 'eo\n    at Object.signTx (chrome-extension://gafhhk…jkeiendhlofajokpaflmk/js/background.js:104:450366'}
```

And similarly to #34 I'm not able to catch proper [`TxSignErrorCode`](https://github.com/cardano-foundation/CIPs/tree/master/CIP-0030#txsignerror) rejection.

**Comment by Titan-C** [comment]
How can I upvote this?
I have the same error on the console and can't catch error on the promise.

**Comment by mchappell** [comment]
https://github.com/input-output-hk/lace/pull/524

**Comment by Titan-C** [comment]
This is solved. You should close the issue.
