### ISSUE TITLE
Cannot sign message to get signature

### ISSUE THREAD

**Issue by Sotatek-TaiTruong** [input-output-hk/lace#803]
I used signMessage in useCardano function to get the wallet's signature. but it reported missing password error
![image](https://github.com/input-output-hk/lace/assets/117699295/fca62bf8-f638-4a21-bbbc-93774f7af2b2)

**Comment by Ryun1** [comment]
Also raised by @Crypto2099 via twitter: https://twitter.com/adamKDean/status/1742208272877359160

**Comment by Crypto2099** [comment]
Adding on here, also observing the same behavior using the raw api.signData() function.

Error Stack Trace:
```
"es: Authentication failure: Failed to enter passphrase due to
 Error: Missing passwordObject.getWalletPassword (chrome-extension://gafhhkghbfjjkeiendhlofajokpaflmk/js/background.js:132:813762)
    at handler (chrome-extension://gafhhkghbfjjkeiendhlofajokpaflmk/js/background.js:119:47700)
    at async chrome-extension://gafhhkghbfjjkeiendhlofajokpaflmk/js/background.js:119:43708"
```

![image](https://github.com/input-output-hk/lace/assets/63186174/54038415-280e-4a51-8bd8-4d9a0aca9013)
