### ISSUE TITLE
memo incorrectly encoded in metadata

### ISSUE THREAD

**Issue by matbech** [input-output-hk/lace#978]
The memo is incorrectly encoded as a single string in the meta data (msg).
However, per specification in CIP-20: "The message content has the key "msg": and consists of an **array of individual message-strings**. "
Reference: https://github.com/cardano-foundation/CIPs/blob/master/CIP-0020/README.md

Expected result:
```
{
  "674":
         {
           "msg":
                  [
                    "memo"
                  ]
         }
}
```

Actual result:
```
{
  "674":
         {
           "msg": "memo"
         }
}
```

**Comment by rhyslbw** [comment]
Thanks for the report @matbech. I've just opened a PR to resolve this bug
